gitSafeReplacementChar: '-'
autoCloseIssue: true

branches:
  - label: 'type | bug'
    prefix: bug/
    name: latest
  - label: 'type | documentation'
    prefix: documentation/
    name: latest
  - label: 'type | feature'
    prefix: feature/
    name: latest
  - label: 'type | maintenance'
    prefix:  maintenance/
    name: latest
