spring:
  profiles:    active:    - dev
logging:
  level:
    root: WARN
    org.springframework: WARN     
    org.springframework.boot: INFO
    org.hibernate.SQL: ERROR      
    fr.esupportail.esupstage: INFO  file:    path: /home/xxx/logs/esupstage    name: esupstage.log
    max-history: 365
application:
  title: esupstage
  redirect-url: http://localhost:8080/